[misc]
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

[reflectors]
A = "EJMZALYXVBWFCRQUONTSPIKHGD"
B = "YRUHQSLDPXNGOKMIEBFZCWVJAT"
C = "FVPJIAOYEDRZXWGCTKUQSBNMHL"

[rotors]
I = "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
II = "AJDKSIRUXBLHWTMCQGZNPYFVOE"
III = "BDFHJLCPRTXVZNYEIWGAKMUSQO"
IV = "ESOVPZJAYQUIRHXLNFTGKDCMWB"
V = "VZBRGITYUPSDNHLXAWMJQOFECK"

[notches]
I = "Q"
II = "E"
III = "V"
IV = "J"
V = "Z"